Repository ipt-cryptolabs/fb-labs-2019, pull requests merged in 2020-01, with the labels that each got.

#32 [CP-1] KOROL MICHAEL FB-72: screenshots + code +protocol
  cp_1/KOROL_MICHAEL_FB-72_cp1/H10.png
  cp_1/KOROL_MICHAEL_FB-72_cp1/H30.png
  cp_1/KOROL_MICHAEL_FB-72_cp1/crypto_lab1.py
  cp_1/KOROL_MICHAEL_FB-72_cp1/protocol.pdf
  cp_1/KOROL_MICHAEL_FB-72_cp1/rez.txt
  cp_1/KOROL_MICHAEL_FB-72_cp1/Н20.png
Labels: report_improvements, screenshots_ok

#102 [CP-3] K. Zaigraev (FB-74), A. Novikov (FB-74)
  cp_3/zaigraev_fb74_novikov_fb74_cp3/.gitignore
  cp_3/zaigraev_fb74_novikov_fb74_cp3/Cryptography_lab03.pdf
  cp_3/zaigraev_fb74_novikov_fb74_cp3/cryptolab03.py
  cp_3/zaigraev_fb74_novikov_fb74_cp3/output.txt
  cp_3/zaigraev_fb74_novikov_fb74_cp3/test.txt
Labels: needs_results, report_improvements

#213 [CP-5] A. Len (FB-73), A.Mukhamedzyanov(FB-73)
  cp_1/Len_fb-73_Mukhamedzyanov_fb-73_cp1/H(10).jpg
  cp_1/Len_fb-73_Mukhamedzyanov_fb-73_cp1/H(20).jpg
  cp_1/Len_fb-73_Mukhamedzyanov_fb-73_cp1/H(30).jpg
  cp_5/Len_fb-73_Mukhamedzyanov_fb-73_cp5/rsa.c
  cp_5/Len_fb-73_Mukhamedzyanov_fb-73_cp5/site.c
  cp_5/Len_fb-73_Mukhamedzyanov_fb-73_cp5/Звіт практикуму №5.docx
  cp_5/Len_fb-73_Mukhamedzyanov_fb-73_cp5/Звіт практикуму №5.pdf
Labels: needs_cleanup

#93 [CP-2] V. Gres (FB-71), K.Natsvin (FB-71): Code + Report
  cp_2/gres_fb-71_natsvin_fb-71_cp2/cp2_report.pdf
  cp_2/gres_fb-71_natsvin_fb-71_cp2/decr.py
  cp_2/gres_fb-71_natsvin_fb-71_cp2/enc.py
  cp_2/gres_fb-71_natsvin_fb-71_cp2/wrongletters.txt
Labels: report_improvements

#110 [CP-3] V. Gres (FB-71), K. Natsvin (FB-71)
  cp_3/gres_fb-71_natsvin_fb-71_cp3/cp3_report.pdf
  cp_3/gres_fb-71_natsvin_fb-71_cp3/data.txt
  cp_3/gres_fb-71_natsvin_fb-71_cp3/lab3.py
Labels: needs_results

#122 [CP-2]Kartash(Fb-71)_Tkachuck(Fb-71)
  cp_2/kartash_fb-71_tkachuk_fb-71/ReportLab2.pdf
  cp_2/kartash_fb-71_tkachuk_fb-71/SourceLab2.cpp
Labels: needs_cleanup

#120 [CP-4]Kartash(Fb-71)_Tkachuk(Fb-71)
  cp_4/kartash_fb-71_Tkachuk_fb-71/ReportLab4.pdf
  cp_4/kartash_fb-71_Tkachuk_fb-71/SourceLab4.cpp
Labels: needs_cleanup, report_improvements

#121 [CP-3]Kartash_(Fb-71)Tkachuk_(Fb-71)
  cp_3/Kartash_fb-71_Tkachuk_fb-71/ReportCrypt3.pdf
  cp_3/Kartash_fb-71_Tkachuk_fb-71/function.cpp
  cp_3/Kartash_fb-71_Tkachuk_fb-71/function.h
  cp_3/Kartash_fb-71_Tkachuk_fb-71/main.cpp
Labels: needs_cleanup, report_ok

#183 [CP-5] Semychastnyi (FB-71) Romanuk (FB-71): Code and protocol
  cp_5/Semichastnyi_fb_71_Romanuk_fb_71_cp_5/image_2019-12-23_21-12-07.png
  cp_5/Semichastnyi_fb_71_Romanuk_fb_71_cp_5/lil_5_laba.py
  cp_5/Semichastnyi_fb_71_Romanuk_fb_71_cp_5/Протокол 5.pdf
Labels: needs_results

#128 [CP-4] Makoid(FB-72), Oliferuk(FB-72)
  cp_4/makoid_fb-72_oliferuk_fb-72_cp4/CP-4.pdf
  cp_4/makoid_fb-72_oliferuk_fb-72_cp4/kripta.cpp
Labels: needs_cleanup, needs_report

#140 [CP-3] [Var-15] Soldatova(FB-72), Yashkova(FB-72): Code and Protocol
  cp_3/soldatova_fb-72_yashkova_fb-72_cp3/CRYPTOLab3.pdf
  cp_3/soldatova_fb-72_yashkova_fb-72_cp3/cryptolab3.py
Labels: report_improvements

#189 [CP5]Nesterov_fb-72_Khristichenko_fb-72: Code + results
  cp_5/Nesterov_fb-72_Khristichenko_fb-72_cp5/Screenshot 2020-01-06 at 19.52.23.png
  cp_5/Nesterov_fb-72_Khristichenko_fb-72_cp5/lab_5_new.py
  cp_5/Nesterov_fb-72_Khristichenko_fb-72_cp5/results.txt
Labels: code_improvements

#47 [CP-1] Shyshkin (FB-73), Vitrovich (FB-73) : Code + Scren
  cp_1/shyshkin_fb-73_vitrovich_fb-73_cp1/1.JPG
  cp_1/shyshkin_fb-73_vitrovich_fb-73_cp1/1.txt
  cp_1/shyshkin_fb-73_vitrovich_fb-73_cp1/2.JPG
  cp_1/shyshkin_fb-73_vitrovich_fb-73_cp1/3.JPG
  cp_1/shyshkin_fb-73_vitrovich_fb-73_cp1/main.py
  cp_1/shyshkin_fb-73_vitrovich_fb-73_cp1/protokol_lab01.docx
  cp_1/shyshkin_fb-73_vitrovich_fb-73_cp1/Частоты.txt
  cp_1/shyshkin_fb-73_vitrovich_fb-73_cp1/результат.txt
Labels: needs_cleanup, screenshots_ok

#139 [CP-5] D.Rakovych (FB-73), D. Pekarchuk (FB-74): CP-5 Code and Protocol
  cp_5/pekarchuk_fb_74_rakovych_fb_73/code.py
  cp_5/pekarchuk_fb_74_rakovych_fb_73/protocol.pdf
Labels: needs_results, report_ok

#241 [Cp-2]Ravkin(fb-71),Novyk(fb-71)
  cp_2/ravkin_fb-71_novik_fb-71_cp2/Source.cpp
  cp_2/ravkin_fb-71_novik_fb-71_cp2/Крипта_2лаба_протокол (2).pdf
  cp_2/ravkin_fb-71_novik_fb-71_cp2/Новый текстовый документ.txt
Labels: needs_results

#90 [CP-1] V.Bezludnyi (FB-71), D.Melnyk (FB-71): Protocol and everything else.
  cp_1/bezludnyi_fb-71_cp1/pic01.png
  cp_1/bezludnyi_fb-71_cp1/pic02.png
  cp_1/bezludnyi_fb-71_cp1/pic03.png
  cp_1/bezludnyi_fb-71_melnyk_fb-71_cp_1/Crypto_lab1_protocol.pdf
  cp_1/bezludnyi_fb-71_melnyk_fb-71_cp_1/Source.cpp
  cp_1/bezludnyi_fb-71_melnyk_fb-71_cp_1/bigr.txt
Labels: bad_results

#129 [CP-2]Katrych Daria(FB-72), Marisov Mykola(FB-72)
  cp_2/katrych_fb-72_marisov_fb-72_cp2/OT_var6.txt
  cp_2/katrych_fb-72_marisov_fb-72_cp2/laba2.cpp
  cp_2/katrych_fb-72_marisov_fb-72_cp2/my_CT (5).txt
  cp_2/katrych_fb-72_marisov_fb-72_cp2/my_OT (6).txt
  cp_2/katrych_fb-72_marisov_fb-72_cp2/Протокол2лабаКатричМарисов.pdf
  cp_2/katrych_fb-72_marisov_fb-72_cp2/СT_var6.txt
Labels: needs_cleanup

#186 [CP-3]Katrych Daria, Marisov Mykola (FB-72)
  cp_3/katrychfb-72_marisovfb-72/Protokol3laba.pdf
  cp_3/katrychfb-72_marisovfb-72/laba3.cpp
  cp_3/katrychfb-72_marisovfb-72/out_PT.txt
Labels: code_improvements

#231 [CP_2] Briks FB-74 Sorbot FB-74
  cp_2/Briks_FB-74_Sorbot_FB-74_cp_2/Analis.py
  cp_2/Briks_FB-74_Sorbot_FB-74_cp_2/CRYPT2_PROT.pdf
  cp_2/Briks_FB-74_Sorbot_FB-74_cp_2/Creator.py
  cp_2/Briks_FB-74_Sorbot_FB-74_cp_2/IS.py
  cp_2/Briks_FB-74_Sorbot_FB-74_cp_2/VAR_ENC.txt
  cp_2/Briks_FB-74_Sorbot_FB-74_cp_2/open_text.txt
Labels: needs_cleanup, needs_report
